import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders} from '@angular/common/http';
import { Observable,  } from 'rxjs';


@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor(private http: HttpClient) {

  }




  call(): Observable<any> {
    return this.http.get("https://graph.microsoft.com/beta/me");
  }

  token:any = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IjVCZ1JkYWxuSHZhdlI2eURrM2xnVk9MVEVSd0lpTmI4UW9LZDBrMU1JUk0iLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84ZjZiZDk4Mi05MmMzLTRkZTAtOTg1ZC0wZTI4N2M1NWUzNzkvIiwiaWF0IjoxNjI5OTA4OTY5LCJuYmYiOjE2Mjk5MDg5NjksImV4cCI6MTYyOTkxMjg2OSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyWmdZT0JZOVAwc3I5UjBJOTdsY3ovM2J2Sll1dWhkOXdUNXZqbGRPdjFHVWZ3NWY1a0IiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IktyaXNobmEiLCJnaXZlbl9uYW1lIjoiSmFzdGkiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiI0OS4zNy4xNTguOTAiLCJuYW1lIjoiSmFzdGkgIEtyaXNobmEiLCJvaWQiOiJlNDgyNDU3Mi1iYWU3LTQ1MDYtYjljMC00N2NmMGMwNzcwMjAiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDE2QTEyMTQyRSIsInJoIjoiMC5BVjhBZ3Rscmo4T1M0RTJZWFE0b2ZGWGplYlhJaTk3NTJiRklxSzIzU05weVVHUmZBRjguIiwic2NwIjoib3BlbmlkIFByZXNlbmNlLlJlYWQgcHJvZmlsZSBVc2VyLlJlYWQgZW1haWwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiJyOWpnSGxCY19obEkzZHpTWGI1Wk5rVTc5Sm1KSVkxMm5ET05iWWdZVkZZIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkVVIiwidGlkIjoiOGY2YmQ5ODItOTJjMy00ZGUwLTk4NWQtMGUyODdjNTVlMzc5IiwidW5pcXVlX25hbWUiOiJqa3Jpc2huYUBhcmlxdC5jb20iLCJ1cG4iOiJqa3Jpc2huYUBhcmlxdC5jb20iLCJ1dGkiOiJUMEFFVVJwRkYweXpfQ1BMYWpBQkFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3N0Ijp7InN1YiI6IlBaWHNqZnRHMzZTYVVKaWFOeExWZXByUDJUS3ljSWk2eFRXRkYtTXd5OG8ifSwieG1zX3RjZHQiOjE1OTI4MDc2NzJ9.Nnb2miNm1icVuhTdgZ66VhGmCgmbhf5U0sfcwJq6Z6NjQVJydQ8OBl4_C4xxejoxXPQH1vVnyK4oa-6v45PfuoF6mr-iG7-hMaeLanUWs8171PLD0lyPS2tVB4ft_HtyJSGxM51OIziA7DQ5eMnIzQJ7ytxrA4yH5RJUaAg2SYkrqI-GNE4_E97ivWapx0BPL6HgafrptanGR3bO0BmvTgu7brBL8colVA1R34jIjMJIAPeTZoZevT6iVpMlZaD0f2Xst53g4GPn9oiDY_59QdRBKO6FB4CIC4QQzeMcFMQ_3DR351UWgieaesV62i7jUfwdBwsS2pdNEYImwWXo0A";



  image(): Observable<any> {
    let headers = new HttpHeaders();
    headers.append('Authorization', 'Bearer' + this.token);
    headers.append("content-type","application/json");
    return this.http.get("https://graph.microsoft.com/beta/me/photo/$value", { responseType:'blob' as 'json',
      headers: headers
    });
  }


}
